### ISSUE TITLE
Client-create Task 

### ISSUE THREAD

**Issue by Kibia** [xinra-oss/open-gtd#64]
create Task as popup? Suggestions? @erikhofer  you wanted something like fast access for creating tasks to the inbox ? 
child of #6

**Comment by erikhofer** [comment]
Tasks should be added directly to the task list as an empty line, without a popup.

We can postpone quick entry to inbox for now.

**Comment by Kibia** [comment]
what about the difference between creating an "project" (root task), extra button or logic ?

**Comment by erikhofer** [comment]
A root task is not a project. There should be two buttons:
* Create task → create task at the same level as the selected task (or root task, if no task is selected)
* Create subtask → create task as child of the selected task (disabled if no task is selected)
